### ISSUE TITLE
Writeup for Cool Kicks challenge

### ISSUE THREAD

**Issue by mar232320** [Super-Yojan/FreedomCTFWriteups#1]
Hello, I participated in freedom ctf in june and I greatly enjoyed it. Could you tell me what is the solution of cool kicks challenge? I found out that its truecrypt steganography but doesnt for for rockyou in hashcat

**Comment by Super-Yojan** [comment]
Sorry for the late reply. Yes it is truecrypt, the creator of the challenge lost their notes, and don't remember the password. I think the password was something like `P@ssw0rd` or something similar to that.
